server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: yourSecretKeyHere
  expiration: 3600000
